version: '3.8'

services:
  db:
    image: mysql:8.0.35 
    container_name: my-mysql-db
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persists data outside the container

volumes:
  mysql_data:
    driver: local